version: 2

before:
  hooks:
    - make clean

builds:
  - env:
      - CGO_ENABLED=0
    skip: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: potangpa-sudo
    name: bangkok-aqi-pipeline
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Bangkok AQI Pipeline {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    ## Thanks!
    
    Those were the changes for {{ .Tag }}!
